frameworkVersion: "3"
app: demo
service: analytics-${self:app}

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "sqs:*"
            - "dynamodb:*"
          Resource: "*"
  httpApi:
    cors: true

plugins:
  - serverless-plugin-typescript
  # - serverless-dotenv-plugin

package:
  individually: true

resources:
  Resources:
    # INGEST DATA
    AnalyticsQueueDemoDLQ: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-dlq-${sls:stage}-queue.fifo
        FifoQueue: true
    AnalyticsQueueDemo: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${sls:stage}-queue.fifo
        FifoQueue: true
        MessageRetentionPeriod: 345600 # 4 days
        VisibilityTimeout: 10
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - AnalyticsQueueDemoDLQ
              - Arn
          maxReceiveCount: 5
    AnalyticsDemoDB: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html
      Type: AWS::RDS::DBInstance
      Properties:
        Engine: MySQL
        DBInstanceIdentifier: ${self:service}-${sls:stage}
        DBName: ${env:DATABASE_NAME}
        MasterUsername: admin
        MasterUserPassword: adminPass
        # Port: 3306
        DBInstanceClass: db.t3.micro
        StorageType: gp2
        AllocatedStorage: "20"
        PubliclyAccessible: true
        # MonitoringInterval: 60
        # MonitoringRoleARN: arn:aws:iam::${aws:accountId}:role/rds-monitoring-role
        BackupRetentionPeriod: 7
        StorageEncrypted: true
        EnableCloudwatchLogsExports:
          - audit
          - error
          - general
          - slowquery

    # SUMARIZATION DATA
    BusinessQueueDemoDLQ: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-business-dlq-${sls:stage}-queue.fifo
        FifoQueue: true
    BusinessQueueDemo: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-business-${sls:stage}-queue.fifo
        FifoQueue: true
        MessageRetentionPeriod: 345600 # 4 days
        VisibilityTimeout: 30
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - BusinessQueueDemoDLQ
              - Arn
          maxReceiveCount: 5
    SumarizationQueueDemoDLQ: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-sumarization-dlq-${sls:stage}-queue.fifo
        FifoQueue: true
    SumarizationQueueDemo: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-sumarization-${sls:stage}-queue.fifo
        FifoQueue: true
        MessageRetentionPeriod: 345600 # 4 days
        VisibilityTimeout: 30
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - SumarizationQueueDemoDLQ
              - Arn
          maxReceiveCount: 5
    # TODO: Dynamo Table
    AnalyticsSumarizationTable: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "businessSlug#range#pageName"
            AttributeType: "S"
          -
            AttributeName: "created_at"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "businessSlug#range#pageName"
            KeyType: "HASH"
          -
            AttributeName: "created_at"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
        TableName: ${self:service}-${sls:stage}

functions:
  # INGEST DATA
  producer-analytics-demo-queue:
    handler: src/producers/analyticsQueueProducer.handler
    events:
      - httpApi:
          path: /analytics
          method: post
    timeout: 6 # optional, in seconds, default is 6
    environment:
      ANALYTICS_QUEUE: https://sqs.${aws:region}.amazonaws.com/${aws:accountId}/${self:service}-${sls:stage}-queue.fifo
  consumer-analytics-demo-queue:
    handler: src/consumers/analyticsQueueConsumer.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - AnalyticsQueueDemo
              - Arn
    memorySize: 1024 # optional, in MB, default is 1024
    timeout: 6 # optional, in seconds, default is 6
    environment:
      DATABASE_URL:
        Fn::Join:
          - ""
          - - mysql://${env:DATABASE_USERNAME}:${env:DATABASE_PASSWORD}@
            - !GetAtt AnalyticsDemoDB.Endpoint.Address
            - ":"
            # - !GetAtt AnalyticsDemoDB.Endpoint.Port
            - "${env:DATABASE_PORT}/${env:DATABASE_NAME}"

  # SUMARIZATION DATA
  business-cron-job-demo:
    handler: src/cronjobs/businessCronjob.handler
    events:
      - schedule: cron(0 0 * * ? *)
    timeout: 60 # optional, in seconds, default is 6
    environment:
      RANGES: 7,15,30
      ANALYTICS_BUSINESS_QUEUE: https://sqs.${aws:region}.amazonaws.com/${aws:accountId}/${self:service}-business-${sls:stage}-queue.fifo
      ENDPOINT_CLIENTS: ${env:ENDPOINT_CLIENTS}
  sumarization-business-demo:
    handler: src/cronjobs/sumarizationBusinessCronjob.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - SumarizationQueueDemo
              - Arn
    environment:
      ANALYTICS_TABLE_NAME: ${env:ANALYTICS_TABLE_NAME}
      ANALYTICS_TABLE_SUMARIZATION_NAME: ${self:service}-${sls:stage}
      DATABASE_NAME: ${env:DATABASE_NAME}
      DATABASE_URL:
        Fn::Join:
          - ""
          - - mysql://${env:DATABASE_USERNAME}:${env:DATABASE_PASSWORD}@
            - !GetAtt AnalyticsDemoDB.Endpoint.Address
            - ":"
            # - !GetAtt AnalyticsDemoDB.Endpoint.Port
            - "${env:DATABASE_PORT}/${env:DATABASE_NAME}"
  consumer-sumarization-by-page:
    handler: src/consumers/sumarizationByPageConsumer.handler
    events:
      - httpApi:
          path: /analytics/{businessSlug}/{range}/{pageName}
          method: get
